### ISSUE TITLE
Error: Type 'F' is not supported

### ISSUE THREAD

**Issue by anthonywebb** [yortus/DBFFile#15]
I have a DBF that has some float data in it, getting "Error: Type 'F' is not supported" when reading the data.  I was curious if float data is on the roadmap of supported file types?  I looked at the code and it looks as if I could add another case statement for it, but I am not familiar with any of the gotchas I may run into during the process?  Can you help? @yortus

**Comment by yortus** [comment]
@anthonywebb I'm sorry I never got back to you about this. I suppose you have found a workaround since opening this issue. In case you are still interested in adding float support, it should be fairly straightforward. However, I don't have any dbf files with float columns to test with. If you have anything that can go in the test fixtures that would be great.

**Comment by yortus** [comment]
The 'F' field type is now supported in v1.1.
