### ISSUE TITLE
Can I update a specific row?

### ISSUE THREAD

**Issue by meilechwieder** [yortus/DBFFile#47]
I want to be able to update a specific row.

If updating is for some reason impossible, how about every time we update a row, we just replace all file content of with new updated content? we have the descriptors, we have everything in memory, we just delete the old and create a new with all existing records and the updated ones. Can this feature be built in to the library?

Also what is the file limit this library can handle. Does it just depend on my devices resources?

**Comment by lordrip** [comment]
Hi, regarding the initial question, I guess that this could work just for
standalone purposes since all clients open the file to read / write as
well. Is this your use case?

I'm not the maintainer of the library so I cannot decide (or know 😅)
whether this feature will be included or not, but I think that you can
implement a wrapper on top of the dbffile class in order to flush it out.

**Comment by meilechwieder** [comment]
But maybe just updating a row should be possible, without deleting and recreating. The same like appending a row is possible

**Comment by lordrip** [comment]
Yes, although I think the process is slightly different. As far as I know,
adding a record means append the information and then update the header to
include the newly added record.

In counterpart for updating, in which the process goes like first locking
the record (or the whole file, depending of the mode) and then makes the
update and finally reverse the lock.

So I guess that this is not something that can be made outside of the
library (although extending the dbffile class would be possible)

Long time ago I've wanted to implement something similar but unfortunately
couldn't find enough time to do so 😞

**Comment by yortus** [comment]
Hi @meilechwieder,

> what is the file limit this library can handle. Does it just depend on my devices resources?

In principle there is no limit, even on machines with tight resources. The design allows for reading/writing batches of rows in manageable-sized chunks, so there's no need for the file to be all in memory at once.

> But maybe just updating a row should be possible, without deleting and recreating. The same like appending a row is possible

Sure, it would be possible. There are a few reasons it has not been implemented so far:
- I didn't have that use-case. I only needed batch reading and writing. So that's what got initially implemented.
- Reading and appending are 'safer' in that you don't need to alter existing dbf files. In order to safety update rows in-place, a number of additional factors come into play. E.g., are there separate index files to maintain? Memo files to update? Do we need row locks for safe concurrent access? Might we corrupt the original file due to not supporting a file format quirk?

At present the library gets by with limited support for all the possible file formats and protocols. I think it's a much bigger task to support general row-level read/update in a library that is expected to be robust (I imagine at that point some would want to use it as a simple DB backend).

A PR would be welcome if anyone wants to tackle this in a robust manner.

In the meantime, I'd do it as you originally suggested. Read rows from the input file, and write them back out to a new output file, updating some rows before appending them to the new file. It's basically a batch update operation. It's not very 'interactive' but then again these are ancient file formats. For truly interactive applications, they should probably be batch-imported into a more modern DB.

**Comment by yortus** [comment]
Closing as 'wontfix' for now. A PR would be welcome if it can solve this issue in a robust way.
